model_name: "facebook/opt-125m"
dataset_path: "src/mtl4ad/resources/train/dataset"
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_checkpointing: true
gradient_accumulation_steps: 1
model_max_length: 512
experiment_name: train_7
checkpoint_dir: "models"
deepspeed: "configs/deepspeed_config.json"
dataset_percentage: 0.1
dataset_seed: 42
shuffle: true
enable_peft: true
eval_steps: 500
logging_steps: 100
save_total_limit: 10
save_steps: 100
eval_strategy: "steps"
num_train_epochs: 1
report_to: "mlflow"